language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

jobs:
  include:
    - name: "Linter"
      script:
        - docker-compose run --rm app sh -c "flake8"

    - name: "Django Test"
      script:
        - docker-compose run --rm app sh -c "pytest"