language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

jobs:
  include:
    - name: "Linter"
      script:
        - docker-compose run --rm app sh -c "flake8"

    - name: "Django Test"
      before_script:
        - docker-compose -v
        - docker -v
        # Ensure celerybeat does not crash due to non-existent tables
        - docker-compose run --rm app sh -c "python manage.py migrate"
      script:
        - docker-compose run --rm app sh -c "pytest && flake8"