language: python
python:
  - "3.9"

services:
  - docker

before_script: pip install docker-compose

jobs:
  include:
    - name: "Linter"
      before_script:
        - pip install -q flake8
      script:
        - "flake8"

    - name: "Django Test"
      script:
        - docker-compose run app sh -c "pytest"
      after_failure:
        - docker-compose -f local.yml logs
