# Generated by Django 3.2.5 on 2021-07-12 13:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='recipe title')),
                ('time_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='preparation time in minutes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price in USD')),
                ('link', models.URLField(blank=True, max_length=255, verbose_name='Optional URL')),
                ('ingredients', models.ManyToManyField(to='core.Ingredient')),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
