# Generated by Django 3.2.5 on 2021-07-13 07:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
